#spring:
#  datasource:
#    hikari:
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      jdbc-url: jdbc:oracle:thin:@//localhost:1521:orcl2
#      username: test
#      password: test
#      maximum-pool-size: 20
#      idle-timeout: 10000
#
#
#jdbcUrl: jdbc:oracle:thin:@//localhost:1521:orcl2

org.hibernate.envers.audit_table_suffix: _AUD