  ,'نامشخص'  superior_dep
  ,'-1'      superior_dep_code
  ,'نامشخص' department
  ,'-1' dep_code
  ,-1 dep_type
  ,-1 dep_box_id
  ,'نامشخص' dep_box_name
  ,-1 dep_batch_id
  ,'نامشخص' dep_batch_name
